Remove all references to /tmp/ in test scripts

diff --git a/scripts/error_test b/scripts/error_test
--- a/scripts/error_test
+++ b/scripts/error_test
@@ -6,18 +6,18 @@ then
   exit
 fi
 
-mkdir -p /tmp/error_outputs
+mkdir -p ./test/error_outputs
 
 for file in $(ls -1 ./examples/errors/programs | grep -v "~"); do
-    ./target/debug/dummyc "./examples/errors/programs/$file" 2> "/tmp/error_outputs/${file%.*}_output" 1> /dev/null
+    ./target/debug/dummyc "./examples/errors/programs/$file" 2> "./test/error_outputs/${file%.*}_output" 1> /dev/null
 done
 
 if [ $1 -eq 0 ]
 then
-    for file in $(ls -1 /tmp/error_outputs | grep -v "~"); do
-	cat "/tmp/error_outputs/$file" | grep "error" > "/tmp/error_outputs/${file}_post"
-	diff "./examples/errors/outputs/error_output" "/tmp/error_outputs/${file}_post" > "/tmp/diff"
-	echo -n "$file: " && [ -s /tmp/diff ] && (echo "fail") || (echo "pass")
+    for file in $(ls -1 ./test/error_outputs | grep -v "~"); do
+	cat "./test/error_outputs/$file" | grep "error" > "./test/error_outputs/${file}_post"
+	diff "./examples/errors/outputs/error_output" "./test/error_outputs/${file}_post" > "./test/diff"
+	echo -n "$file: " && [ -s ./test/diff ] && (echo "fail") || (echo "pass")
     done
 fi
 
@@ -27,11 +27,11 @@ then
     num_fail=0
     num_total=0
 
-    for file in $(ls -1 /tmp/error_outputs | grep -v "~"); do
-	cat "/tmp/error_outputs/$file" | grep "error" > "/tmp/error_outputs/${file}_post"
-	diff "./examples/errors/outputs/error_output" "/tmp/error_outputs/${file}_post" > "/tmp/diff"
+    for file in $(ls -1 ./test/error_outputs | grep -v "~"); do
+	cat "./test/error_outputs/$file" | grep "error" > "./test/error_outputs/${file}_post"
+	diff "./examples/errors/outputs/error_output" "./test/error_outputs/${file}_post" > "./test/diff"
 	num_total=$(( $num_total + 1 ))
-	[ -s /tmp/diff ] && num_fail=$(( $num_fail + 1 )) || num_pass=$(( $num_pass + 1 ))
+	[ -s ./test/diff ] && num_fail=$(( $num_fail + 1 )) || num_pass=$(( $num_pass + 1 ))
     done
 
     echo "Total:" $num_total
@@ -47,4 +47,4 @@ then
     echo "=> failed:" $num_fail
 fi
 
-rm -r /tmp/error_outputs/
+rm -r ./test
diff --git a/scripts/nbs_test b/scripts/nbs_test
--- a/scripts/nbs_test
+++ b/scripts/nbs_test
@@ -6,15 +6,17 @@ then
   exit
 fi
 
+mkdir ./test
+
 for file in $(ls -1 ./examples/nbs/programs | grep -v "~"); do
-    ./target/debug/dummyc "./examples/nbs/programs/$file" 1> "/tmp/${file%.*}_output" 2> /dev/null
+    ./target/debug/dummyc "./examples/nbs/programs/$file" 1> "./test/${file%.*}_output" 2> /dev/null
 done
 
 if [ $1 -eq 0 ]
 then
     for file in $(ls -1 ./examples/nbs/outputs | grep -v "~"); do
-	diff "./examples/nbs/outputs/$file" "/tmp/$file" > "/tmp/diff"
-	echo -n "$file: " && [ -s /tmp/diff ] && (echo "fail") || (echo "pass")
+	diff "./examples/nbs/outputs/$file" "./test/$file" > "./test/diff"
+	echo -n "$file: " && [ -s ./test/diff ] && (echo "fail") || (echo "pass")
     done
 fi
 
@@ -22,7 +24,7 @@ if [ $1 -eq 1 ]
 then
     for file in $(ls -1 ./examples/nbs/outputs | grep -v "~"); do
 	echo "~~~~~~~~~~> $file: "
-	cat "/tmp/$file"
+	cat "./test/$file"
     done
 fi
 
@@ -33,9 +35,9 @@ then
     num_total=0
 
     for file in $(ls -1 ./examples/nbs/outputs | grep -v "~"); do
-	diff "./examples/nbs/outputs/$file" "/tmp/$file" > "/tmp/diff"
+	diff "./examples/nbs/outputs/$file" "./test/$file" > "./test/diff"
 	num_total=$(( $num_total + 1 ))
-	[ -s /tmp/diff ] && num_fail=$(( $num_fail + 1 )) || num_pass=$(( $num_pass + 1 ))
+	[ -s ./test/diff ] && num_fail=$(( $num_fail + 1 )) || num_pass=$(( $num_pass + 1 ))
     done
 
     echo "Total:" $num_total
@@ -50,3 +52,5 @@ then
     echo "=> passed:" $num_pass
     echo "=> failed:" $num_fail
 fi
+
+rm -r ./test
